name: pr
on:
    pull_request
jobs:
    lint:
        name: Check that it conforms to the style guide
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Install missing tools
              run: |
                install_dir=/usr/local/bin

                # Install shfmt
                shfmt_version=v3.1.2
                shfmt_checksum=c5794c1ac081f0028d60317454fe388068ab5af7740a83e393515170a7157dce
                sudo curl --location --silent --fail --tlsv1.2 --proto '=https' \
                    --output "$install_dir"/shfmt \
                    https://github.com/mvdan/sh/releases/download/"$shfmt_version"/shfmt_"$shfmt_version"_linux_amd64
                sha256sum -c <(echo "$shfmt_checksum $install_dir/shfmt") > /dev/null 2>&1
                sudo chmod a+x "$install_dir"/shfmt

                # Install Shellcheck (Ubuntu’s version is too old)
                shellcheck_version=v0.7.1
                shellcheck_checksum=64f17152d96d7ec261ad3086ed42d18232fcb65148b44571b564d688269d36c8  
                shellcheck_arname=shellcheck.tar.xz
                curl --location --silent --fail --tlsv1.2 --proto '=https' \
                    --output "$shellcheck_arname" \
                    https://github.com/koalaman/shellcheck/releases/download/"$shellcheck_version"/shellcheck-"$shellcheck_version".linux.x86_64.tar.xz
                sha256sum -c <(echo "$shellcheck_checksum $shellcheck_arname") > /dev/null 2>&1
                tar -xf "$shellcheck_arname" --strip-components=1 \
                    shellcheck-"$shellcheck_version"/shellcheck
                rm "$shellcheck_arname"
                chmod a+x shellcheck
                sudo chown root:root shellcheck
                sudo mv shellcheck "$install_dir"
            - name: Check formatting
              run: make format
            - name: Check for erroneous constructs
              run: make lint
    pr:
        name: Check that it builds without error
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Install missing tools
              run: sudo apt-get install bsdtar tree
            - name: Build packages
              run: make repo-new
            - name: Save the build output
              uses: actions/upload-artifact@v2
              with:
                name: repo
                path: build/repo
